[technote]
id = "SITCOMTN-107"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-107.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-107"
github_default_branch = "main"
date_created = 2024-01-22T13:27:09Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Craig S."
name.family = "Lage"
orcid = "0000-0002-9601-345X"
internal_id = "lagecs"
[[technote.authors.affiliations]]
name = "Physics Department"
internal_id = "UCDavis"
address = "University of California, One Shields Avenue, Davis, CA 95616, USA"
